inits esling config + prettier #4
EveryonesInvited/website pull request #15
Opened 2021-05-03 19:35 UTC by LDNCWRB

### What changes have you made?

- Installed eslint + eslint.json updates

### Which issue(s) does this PR fix?

- Fixes #4 

### Screenshots (if there are design changes)

### How to test 

- Format on save

2021-05-03 20:16 UTC, Jbarget requested changes
can we add `eslint-plugin-jsx-a11y` too and use it like below

![image](https://user-images.githubusercontent.com/11725595/116928265-c1961180-ac54-11eb-870c-547131867163.png)

2021-05-03 20:16 UTC, Jbarget commented on .eslintrc.json
> +    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }], //should add ".ts" if typescript project
we need to do what the comment says and add `.ts` and `.tsx` into the array

2021-05-04 08:14 UTC, Jbarget commented
can we delete the `package-lock.json` file too :)

2021-05-04 11:35 UTC, Jbarget commented
when there are merge conflicts with lock files **never** go in and manually sort the conflicts out, just delete the lock file (`yarn.lock` or `package-lock.json`) and run `yarn` if you're using yarn or `npm i` if you're using npm

so in this case:
sort out the package.json conflicts, then follow the steps above

2021-05-04 11:36 UTC, Jbarget commented
do eslint/typescript errors show as expected for you on this branch? I checked last night and it wasn't for me

2021-05-04 11:38 UTC, raphaelj274 commented
> do eslint/typescript errors show as expected for you on this branch? I checked last night and it wasn't for me

they don't because ts and eslint were not installed on this branch, now that setup is merged we will pull and rebase to check if its working

2021-05-04 11:54 UTC, raphaelj274 commented
sorry, need to look at the package json again

2021-05-04 13:56 UTC, raphaelj274 commented
> do eslint/typescript errors show as expected for you on this branch? I checked last night and it wasn't for me

typescript errors working but were not sure how to check for eslint errors as surely prettier is getting rid of them on save?

2021-05-04 14:02 UTC, Jbarget commented
if you make an eslint error but dont save then you should still see the error

2021-05-04 14:03 UTC, Jbarget commented
when this is ready for re-review click the circular arrows next to my name in the reviewers column, thats how you would let me know when to review again

![image](https://user-images.githubusercontent.com/11725595/117015681-dec8ef80-ace9-11eb-8a4a-ee711fd9a424.png)

2021-05-04 14:52 UTC, raphaelj274 commented
hey we're a bit stuck on setting up eslint, we're gonna try create the form in the meantime, but when you have a chance could we go over this?

2021-05-06 15:57 UTC, Jbarget commented
this PR can be closed and the branch deleted once #19 goes in

2021-05-07 13:48 UTC, closed without merging